"use client";
import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const activeChainId = ChainId.Localhost;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(children, "first");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThirdwebProvider
          clientId="c3e5c30e3281536429192e2ce3b75b7f"
          activeChain="sepolia"
        >
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
